baseURL = "https://blog.shankarajayaabadi.co.id/"
languageCode = "id"
title = "Agen & Aplikator Plafon PVC & Wall Panel PVC Bengkulu | Desain Modern & Harga Terjangkau"
theme = "saeseen-hugo"
summaryLength = 25

[pagination]
  pagerSize = 6

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  category = "/:slug/"

[params]
  # Site-wide settings
  meta_description = "Spesialis Plafon PVC & Wall Panel PVC di Bengkulu - Tahan Lama, Anti Rayap, Anti Air. Solusi Interior Modern untuk Hunian, Perkantoran, dan Bisnis Anda di seluruh wilayah Bengkulu."
  viewport = "width=device-width, initial-scale=1.0"
  fontawesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
  logo = "/images/logo/Shankara-logo120x80.png"
  logo_amp = "/images/logo/Shankara-logo512x512.png"
  footer_logo = "/images/logo/Shankara-logo120x80-putih.png"
  favicon = "/images/logo/Shankara-logo512x512.png"
  featured_image = "/images/admin/featured-image.png"
  author = "K. Duhri"
  telepon = "//+6281279947777"
  whatsapp = "//api.whatsapp.com/send?phone=6281279947777&text=*Halo shankarajayaabadi.co.id*%20%3A"
  enableWhatApps = true
  enableTelepon = true
  tocMinWordCount = 300
  tableOfContent = "Daftar Isi:"
  geo_latitude = -3.800440
  geo_longitude = 102.265541
  opening_hours = "Mo-Sa 08:00-17:00"

  # Schema settings
  keywords = ["plafon pvc bengkulu", "wall panel pvc bengkulu", "plafon anti rayap bengkulu", "plafon tahan air bengkulu", "wall pvc modern bengkulu", "aplikator plafon bengkulu"]
  base_price = 85000
  price_range = 35000
  free_consultation = true
  service_types = [
    "Plafon PVC Modern Tahan Lama",
    "Plafon PVC Anti Rayap & Anti Air",
    "Wall Panel PVC Interior & Eksterior",
    "Plafon PVC Motif Kayu Premium",
    "Desain Plafon Minimalis Modern"
  ]
  categories = ["Plafon PVC Bengkulu", "Wall Panel PVC", "Desain Interior Bengkulu"]
  payment_methods = ["Transfer Bank", "Bayar Bertahap", "DP 40%", "Cash on Delivery"]
  cancellation_policies = [
    "Pembatalan dapat dilakukan sebelum pemasangan dimulai.",
    "Pengembalian dana penuh jika hasil pemasangan tidak sesuai kesepakatan.",
    "Revisi gratis untuk pemasangan yang kurang rapi atau tidak sesuai permintaan."
  ]
  area_served = [
    "Kota Bengkulu",
    "Bengkulu Tengah",
    "Bengkulu Selatan",
    "Bengkulu Utara",
    "Kaur",
    "Kepahiang",
    "Lebong",
    "Muko-Muko",
    "Rejang Lebong",
    "Seluma"
  ]
  service_output = "Interior rumah, kantor, dan usaha tampil modern, nyaman, dan elegan dengan plafon & wall panel PVC berkualitas di Bengkulu."

 # Hero Section
  hero_image = "/images/admin/bg-hero-bengkulu.jpg"
  hero_title = "Plafon PVC & Wall Panel PVC Bengkulu"
  hero_description = "Percantik interior Anda di Bengkulu dengan Plafon PVC & Wall Panel PVC anti rayap, anti air, dan desain modern. Pilihan motif eksklusif, pemasangan profesional, dan konsultasi gratis untuk setiap kebutuhan renovasi Anda."
  hero_cta_text = "Konsultasi Gratis Bengkulu"
  services_cta_text = "Lihat Produk & Promo"

# Footer Section
  footer_about_title = "Keunggulan Layanan Bengkulu"
  footer_about_description = "Kami menghadirkan plafon & wall panel PVC berkualitas tinggi untuk seluruh wilayah Bengkulu. Material awet, desain kekinian, pemasangan cepat, dan garansi resmi untuk kepuasan Anda."
  footer_services_title = "Mengapa Pilih Kami"
  footer_contact_title = "Kontak Bengkulu"
  footer_bottom_text = "@2025 shankarajayaabadi.co.id | Bengkulu | All Rights Reserved"

  # Testimonials Section
  testimonials_title = "Testimoni Pelanggan Bengkulu"

  [[params.footer_services]]
  text = "blog.shankarajayaabadi.co.id menawarkan solusi plafon dan wall panel PVC dengan desain modern, material premium, serta layanan konsultasi dan pemasangan profesional di seluruh Bengkulu. Percayakan kebutuhan interior Anda pada tim ahli kami."

  [[params.footer_contact]]
    icon = "fas fa-map-marker-alt"
    text = "Jl. Hibrida, Sido Mulyo, Kec. Gading Cemp., Kota Bengkulu, Bengkulu 38225"
  [[params.footer_contact]]
    icon = "fas fa-phone-alt"
    text = "+62 812-7994-7777"
  [[params.footer_contact]]
    icon = "fas fa-envelope"
    text = "shankarajayaabadi.official1@gmail.com"

[[params.testimonials]]
  avatar = "/images/admin/avatar1.png"
  name = "{Andi|Fikri|Rizal|Dedi|Rian|Bagus|Rendy|Yusuf|Fikri|Reza}"
  message = "{Pelayanan dari blog.shankarajayaabadi.co.id {sangat ramah|profesional|responsif}. Hasil pemasangan plafon PVC di rumah saya {sangat memuaskan|rapi|modern sekali}.|Saya {sangat puas|terkesan|senang} dengan kualitas produk dan pemasangan yang {cepat|bersih|tepat waktu}.}"
  response = "{Terima kasih atas {kepercayaan|pilihan} Anda! Kami selalu berusaha memberikan {hasil terbaik|layanan maksimal} untuk pelanggan di Bengkulu.|Kami {mengapresiasi|berterima kasih atas} ulasan Anda. Senang bisa membantu mewujudkan interior impian Anda.}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar2.png"
  name = "{Putri|Nadia|Vina|Citra|Mega|Indah|Tia|Rani|Della|Salsa}"
  message = "{Saya memilih blog.shankarajayaabadi.co.id karena {banyak pilihan motif|harga bersaing|testimoni bagus}. Hasil pemasangan {sangat rapi|presisi|memuaskan} dan timnya {ramah|profesional|berpengalaman}.|Wall panel PVC yang dipasang {membuat rumah lebih nyaman|menambah estetika ruangan|terlihat lebih modern}. Proses konsultasi juga {mudah|jelas|membantu}.}"
  response = "{Terima kasih atas ulasannya! Kami senang Anda puas dengan {produk|layanan} kami.|Kami {bangga|gembira} dapat membantu Anda menemukan plafon PVC yang {tepat|cocok} untuk rumah Anda di Bengkulu.}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar3.png"
  name = "{Adi|Rama|Fajar|Dian|Yoga|Rian|Gilang|Taufik|Bima|Rizal}"
  message = "{Proses pemasangan plafon PVC {sangat cepat|tepat waktu|tanpa kendala} dan hasilnya {sangat bagus|rapi|memuaskan}.|Saya {merekomendasikan|menyarankan} blog.shankarajayaabadi.co.id untuk siapa saja yang ingin {plafon berkualitas|interior modern|hasil maksimal} di Bengkulu.}"
  response = "{Kami {senang|gembira} dapat memenuhi harapan Anda. Terima kasih atas {kepercayaan|pilihan} Anda!|Terima kasih telah merekomendasikan layanan kami di Bengkulu. Kami akan terus {meningkatkan|mempertahankan} kualitas.}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar4.png"
  name = "{Sari|Lestari|Mira|Dewi|Yuni|Aulia|Nisa|Rosa|Dina|Alya}"
  message = "{Plafon PVC dari blog.shankarajayaabadi.co.id {membuat ruangan lebih elegan|menambah nilai estetika|tampak mewah}. Tim pemasangan {sangat teliti|profesional|ramah} dan hasilnya {memuaskan|rapi|presisi}.|Saya {sangat puas|terkesan|senang} dengan pelayanan dan kualitas produk yang diberikan.}"
  response = "{Terima kasih atas kepercayaannya! Kami selalu berusaha memberikan {hasil terbaik|layanan maksimal} untuk pelanggan di Bengkulu.|Kami {menghargai|berterima kasih atas} ulasan Anda. Senang dapat membantu mewujudkan interior impian Anda.}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar5.png"
  name = "{Bayu|Hendra|Toni|Agung|Dedi|Yanto|Wawan|Rio|Iwan|Galih}"
  message = "{Saya memilih blog.shankarajayaabadi.co.id karena {proses konsultasi mudah|harga transparan|tim profesional}. Hasil pemasangan {sangat memuaskan|rapi|tepat waktu} dan kualitas plafonnya {terbaik|premium|tahan lama}.|Plafon PVC yang dipasang {menambah kenyamanan|membuat ruangan lebih modern|sangat sesuai harapan}.}"
  response = "{Terima kasih atas ulasannya! Kami senang dapat membantu proyek Anda.|Kami {mengapresiasi|berterima kasih atas} kepercayaan Anda. Semoga plafon PVC kami selalu memberikan kenyamanan di Bengkulu.}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar6.png"
  name = "{Dewi|Nina|Rina|Maya|Lina|Sari|Fitri|Nur|Diah|Ayu}"
  message = "{Pelayanan dari blog.shankarajayaabadi.co.id {sangat ramah|profesional|membantu}. Plafon PVC yang dipasang {sangat cocok|ideal|sesuai} dengan desain rumah saya.|Saya {senang|puas|terkesan} dengan hasil pemasangan dan kualitas produk yang diberikan.}"
  response = "{Kami {senang|gembira} mendengar Anda puas dengan layanan kami. Terima kasih atas {kepercayaan|pilihan} Anda!|Terima kasih telah memilih produk kami. Kami akan terus memberikan yang terbaik untuk pelanggan di Bengkulu.}"
  rating = 5

[[params.tabelItems]]
  name = "Plafon PVC Modern Tahan Lama"
  price = "360.000 /m²"
[[params.tabelItems]]
  name = "Plafon PVC Anti Rayap"
  price = "390.000 /m²"
[[params.tabelItems]]
  name = "Wall Panel PVC Interior"
  price = "380.000 /m²"
[[params.tabelItems]]
  name = "Wall Panel PVC Eksterior"
  price = "430.000 /m²"
[[params.tabelItems]]
  name = "Plafon PVC Motif Kayu Premium"
  price = "410.000 /m²"

[params.appliList]
  "Plafon PVC Modern Tahan Lama" = "ruang tamu, ruang keluarga, kamar tidur, aula"
  "Plafon PVC Anti Rayap" = "dapur, restoran, area publik, kantor"
  "Wall Panel PVC Interior" = "dinding ruang tamu, partisi kantor, ruang meeting"
  "Wall Panel PVC Eksterior" = "teras, balkon, fasad bangunan, area outdoor"
  "Plafon PVC Motif Kayu Premium" = "villa, resort, hotel, rumah mewah"

[params.kegunaanList]
  "Plafon PVC Modern Tahan Lama" = "perlindungan optimal dari rayap dan kelembapan"
  "Plafon PVC Anti Rayap" = "keamanan ekstra dengan material anti rayap"
  "Wall Panel PVC Interior" = "menciptakan suasana modern dan elegan di dalam ruangan"
  "Wall Panel PVC Eksterior" = "perlindungan dari cuaca ekstrem dan sinar UV"
  "Plafon PVC Motif Kayu Premium" = "tampilan natural dan mewah dengan motif kayu eksklusif"

  # Menu Section
  [[params.menu_items]]
    title = "Beranda"
    url = "/"
  [[params.menu_items]]
    title = "Tentang Kami"
    url = "https://shankarajayaabadi.co.id/profile/"
  [[params.menu_items]]
    title = "Harga & Katalog"
    url = "https://shankarajayaabadi.co.id/daftar-harga/"

[params.header]
   title = "Agen & Aplikator Plafon/Wall PVC Bengkulu | "
   highlight = "PT. SHANKARA JAYA ABADI"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[outputFormats]
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp/index"
    path = ""
    isPlainText = false
    permalinkable = true
    rel = "amphtml"
